name: ocr_microservice_cpu_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch==1.13.1
  - torchvision==0.14.1
  - cpuonly
  - transformers
  - evaluate
  - tensorboard
  - pycocotools
  - lightning
  - pytorch-lightning
  - pip
  - pip:
    - torchaudio==0.13.1
    - paddlepaddle==2.5.2
    - paddleocr
    - "transformers[torch]"
    - segformer-pytorch
    - pytest
    - pika
    - pdf2image
