apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-microservice-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ocr-microservice
  template:
    metadata:
      labels:
        app: ocr-microservice
    spec:
      containers:
      - name: ocr-microservice
        image: europe-west1-docker.pkg.dev/mad-hbs/budget-server/ocr_microservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq" 
        volumeMounts:
        - name: image-storage
          mountPath: "/mnt/images"
      volumes:
      - name: image-storage
        persistentVolumeClaim:
          claimName: image-storage-pvc
